from screen.splash_screen import SplashScreen
from screen.learning_screen import LearningScreen
from screen.calibration_screen import CalibrationScreen
from screen.prediction_screen import PredictionScreen
from screen.info_screen import InfomationScreen
